services:
  postgres:
    image: postgres:18-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_USER: prasun
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5434:5432"
    volumes:
      - prasun_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prasun -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  prasun_postgres: